name: publish github pages
on:
  push:
    branches: [main]
env:
  FACEBOOK_CLIENT_ID: ${{ serects.FACEBOOK_CLIENT_ID }}
  FACEBOOK_CLIENT_SECRET: ${{ serects.FACEBOOK_CLIENT_SECRET }}
  FACEBOOK_LONG_LIVE_TOKEN: ${{ serects.FACEBOOK_LONG_LIVE_TOKEN }}
  FACEBOOK_TEST_EMAIL: ${{ serects.FACEBOOK_TEST_EMAIL }}
  GOOGLE_CLIENT_ID: ${{ serects.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ serects.GOOGLE_CLIENT_SECRET }}
  GOOGLE_REFRESH_TOKEN: ${{ serects.GOOGLE_REFRESH_TOKEN }}
  GOOGLE_TEST_EMAIL: ${{ serects.GOOGLE_TEST_EMAIL }}
  
jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn
      - run: yarn test:coverage
      - name: push
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git config --global user.name 'denz93'
          git config --global user.email 'bdnhan182@gmail.com'
          git fetch
          git checkout gb_pages
          mkdir -p ./docs
          cp -R ./coverage/* ./docs
          git add docs/*
          git commit -m "Update page"
          git push