name: Publish Package to npmjs
on:
  push:
    branches: main
env:
  FACEBOOK_CLIENT_ID: ${{ secrets.FACEBOOK_CLIENT_ID }}
  FACEBOOK_CLIENT_SECRET: ${{ secrets.FACEBOOK_CLIENT_SECRET }}
  FACEBOOK_LONG_LIVE_TOKEN: ${{ secrets.FACEBOOK_LONG_LIVE_TOKEN }}
  FACEBOOK_TEST_EMAIL: ${{ secrets.FACEBOOK_TEST_EMAIL }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ serects.GOOGLE_CLIENT_SECRET }}
  GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
  GOOGLE_TEST_EMAIL: ${{ secrets.GOOGLE_TEST_EMAIL }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn
      - run: yarn test
      - run: yarn build
  bump_version:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      tag_version: ${{ steps.bump.outputs.newTag }}
    steps:
      - id: checkout
        uses: actions/checkout@v3
      - id: bump
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          minor-wording: 'add,Adds,new'
          major-wording: 'MAJOR,cut-major'
          patch-wording: 'patch,fixes'
          tag-prefix: 'v'

  publish:
    needs: bump_version
    runs-on: ubuntu-latest
    env:
      newTag: ${{ needs.bump_version.outputs.tag_version }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.newTag }}
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - run: yarn build
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}